import { Patient, TherapySession, Task, Material, ClinicalRecord, WhatsAppLog, DashboardStats } from "@/types";

export const mockPatients: Patient[] = [
  {
    id: "1",
    name: "María",
    lastName: "González",
    email: "maria.gonzalez@email.com",
    phone: "+56912345678",
    birthDate: new Date("1990-03-15"),
    notes: "Paciente con ansiedad generalizada. Progreso notable en las últimas sesiones.",
    status: "ACTIVE",
    psychologistId: "psy-1",
    tags: ["ansiedad", "adulto", "online"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: "2",
    name: "Carlos",
    lastName: "Mendoza",
    email: "carlos.mendoza@email.com",
    phone: "+56987654321",
    birthDate: new Date("1985-07-22"),
    notes: "Depresión leve. Terapia cognitivo-conductual.",
    status: "ACTIVE",
    psychologistId: "psy-1",
    tags: ["depresión", "adulto", "presencial"],
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-04-28"),
  },
  {
    id: "3",
    name: "Valentina",
    lastName: "Torres",
    email: "valentina.torres@email.com",
    phone: "+56911223344",
    status: "ACTIVE",
    psychologistId: "psy-1",
    tags: ["autoestima", "joven-adulta"],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-05-02"),
  },
  {
    id: "4",
    name: "Diego",
    lastName: "Ramírez",
    email: "diego.ramirez@email.com",
    phone: "+56944556677",
    status: "PAUSED",
    psychologistId: "psy-1",
    tags: ["estrés", "laboral"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-04-10"),
  },
  {
    id: "5",
    name: "Sofía",
    lastName: "Muñoz",
    email: "sofia.munoz@email.com",
    phone: "+56955667788",
    status: "ACTIVE",
    psychologistId: "psy-1",
    tags: ["trauma", "adulto"],
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-05-03"),
  },
];

export const mockSessions: TherapySession[] = [
  {
    id: "s1",
    patientId: "1",
    patient: mockPatients[0],
    psychologistId: "psy-1",
    title: "Sesión de seguimiento",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 2),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 3),
    status: "SCHEDULED",
    type: "ONLINE",
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    createdAt: new Date(),
  },
  {
    id: "s2",
    patientId: "2",
    patient: mockPatients[1],
    psychologistId: "psy-1",
    title: "Sesión de evaluación",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 24),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 25),
    status: "SCHEDULED",
    type: "PRESENTIAL",
    createdAt: new Date(),
  },
  {
    id: "s3",
    patientId: "3",
    patient: mockPatients[2],
    psychologistId: "psy-1",
    title: "Sesión terapia grupal",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 48),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 49),
    status: "SCHEDULED",
    type: "ONLINE",
    meetingUrl: "https://zoom.us/j/123456789",
    createdAt: new Date(),
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Diario emocional semanal",
    description: "Escribe cómo te sientes cada día durante esta semana. Presta atención a las emociones que surgen y qué las provoca.",
    type: "EMOTIONAL_DIARY",
    patientId: "1",
    patient: mockPatients[0],
    psychologistId: "psy-1",
    status: "IN_PROGRESS",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    updatedAt: new Date(),
  },
  {
    id: "t2",
    title: "Ejercicio de respiración 4-7-8",
    description: "Practica la técnica de respiración 4-7-8 por 5 minutos al despertar y antes de dormir.",
    type: "CHECKLIST",
    patientId: "2",
    patient: mockPatients[1],
    psychologistId: "psy-1",
    status: "PENDING",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3),
    checklistItems: [
      { id: "c1", label: "Mañana - Lunes", completed: true },
      { id: "c2", label: "Noche - Lunes", completed: true },
      { id: "c3", label: "Mañana - Martes", completed: false },
      { id: "c4", label: "Noche - Martes", completed: false },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "t3",
    title: "Reflexión: Mis fortalezas",
    description: "Escribe 5 fortalezas personales que identificas en ti mismo. Para cada una, incluye un ejemplo concreto de cuándo la usaste.",
    type: "REFLECTION",
    patientId: "3",
    patient: mockPatients[2],
    psychologistId: "psy-1",
    status: "COMPLETED",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1),
  },
];

export const mockMaterials: Material[] = [
  {
    id: "m1",
    title: "Guía de Mindfulness para principiantes",
    description: "PDF con ejercicios de mindfulness y meditación guiada para practicar en casa.",
    type: "PDF",
    fileUrl: "#",
    category: "Mindfulness",
    psychologistId: "psy-1",
    createdAt: new Date(),
  },
  {
    id: "m2",
    title: "Video: Técnicas de relajación",
    description: "Video de 15 minutos con técnicas de relajación progresiva muscular.",
    type: "VIDEO",
    externalUrl: "https://youtube.com/watch?v=example",
    category: "Relajación",
    psychologistId: "psy-1",
    createdAt: new Date(),
  },
  {
    id: "m3",
    title: "Audio: Meditación guiada",
    description: "Audio de 10 minutos para meditación guiada antes de dormir.",
    type: "AUDIO",
    fileUrl: "#",
    category: "Meditación",
    psychologistId: "psy-1",
    createdAt: new Date(),
  },
  {
    id: "m4",
    title: "Lecturas recomendadas - Autoestima",
    description: "Lista de libros y artículos sobre autoestima y desarrollo personal.",
    type: "LINK",
    externalUrl: "https://notion.so/lectura-autoestima",
    category: "Autoestima",
    psychologistId: "psy-1",
    createdAt: new Date(),
  },
];

export const mockClinicalRecords: ClinicalRecord[] = [
  {
    id: "cr1",
    patientId: "1",
    patient: mockPatients[0],
    psychologistId: "psy-1",
    title: "Evaluación inicial - María González",
    url: "https://drive.google.com/file/example1",
    description: "Ficha de evaluación psicológica inicial. Diagnóstico: F41.1 Trastorno de ansiedad generalizada.",
    tags: ["evaluación", "ansiedad", "2024"],
    date: new Date("2024-01-15"),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "cr2",
    patientId: "1",
    patient: mockPatients[0],
    psychologistId: "psy-1",
    title: "Seguimiento trimestral - María González",
    url: "https://drive.google.com/file/example2",
    description: "Informe de progreso trimestral. Se observa mejoría significativa.",
    tags: ["seguimiento", "2024", "progreso"],
    date: new Date("2024-04-15"),
    createdAt: new Date("2024-04-15"),
  },
  {
    id: "cr3",
    patientId: "2",
    patient: mockPatients[1],
    psychologistId: "psy-1",
    title: "Evaluación inicial - Carlos Mendoza",
    url: "https://notion.so/ficha-carlos",
    description: "Primera evaluación. Derivado por médico tratante.",
    tags: ["evaluación", "depresión", "2024"],
    date: new Date("2024-02-10"),
    createdAt: new Date("2024-02-10"),
  },
];

export const mockWhatsAppLogs: WhatsAppLog[] = [
  {
    id: "wa1",
    patientId: "1",
    patient: mockPatients[0],
    phone: "+56912345678",
    message: "Hola María, te recuerdo que mañana tienes sesión a las 18:00. ¡Te espero! 🌤️",
    status: "SENT",
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "wa2",
    patientId: "2",
    patient: mockPatients[1],
    phone: "+56987654321",
    message: "Hola Carlos, tienes una nueva tarea terapéutica asignada en CloudNimbus.",
    status: "SENT",
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: "wa3",
    patientId: "3",
    patient: mockPatients[2],
    phone: "+56911223344",
    message: "Hola Valentina, recuerda que tu sesión de esta semana fue reagendada para el jueves a las 17:00.",
    status: "SENT",
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalPatients: 5,
  activePatients: 4,
  sessionsThisWeek: 8,
  pendingTasks: 3,
  remindersSent: 12,
  upcomingSessions: mockSessions,
  recentPatients: mockPatients.slice(0, 3),
};
